version: "3.2"
services:
  jaeger-query:
    image: jaegertracing/jaeger-query:1.39.0
    ports:
      - "16686:16686"
    environment:
      - ES_ARCHIVE_TAGS_AS_FIELDS_ALL=true
      - ES_MAX_SPAN_AGE=1440h0m0s
      - ES_NUM_REPLICAS=0
      - ES_NUM_SHARDS=1
      - ES_SERVER_URLS=http://trace-esb-kqdbp.ep-r.io
      - QUERY_ADDITIONAL_HEADERS=Access-Control-Allow-Origin:*
      - SPAN_STORAGE_TYPE=elasticsearch

  logs_authproxy:
    image: quay.io/rapyuta/logs_authproxy:latest
    ports:
      - "8080:8080"
    environment:
      - RIO_TENANT_ID=${RIO_TENANT_ID}
      - TOKEN=${TOKEN}

  jaeger-ui:
    image: quay.io/rapyuta/jaeger-ui:dev
    ports:
      - "9090:9090"
