version: "3.2"
services:
  jaeger-ui:
    image: quay.io/rapyuta/jaeger-ui:dev
    ports:
      - "3000:80"
    environment:
      - CONSOLE_AUTH_URL=https://garip.apps.okd4v2.prod.rapyuta.io
      - CONSOLE_URL=https//gacatalog.apps.okd4v2.prod.rapyuta.io
